### ISSUE TITLE
Libcyrpto.so.1.0.0

### ISSUE THREAD

**Issue by tcleenewerck** [psvensson/firebase-st#4]
I noticed that the creation of the token to acces firebase depends on the module Libcyrpto.so.1.0.0 . However on raspberry pi, that module isn't available. Is there another way to produce the token without using that module?

**Comment by psvensson** [comment]
Libcrypto is a part of openssl, so if you make sure you have a resonably fresh version of opensl istalled, it should contain it. I'm not veyr good at FFI, so I'm not sure if there is anything else one needs to do, but start there and see what happens, would be my recommendation

**Comment by psvensson** [comment]
H, I just wanted to see if you got it working, and if I can close this ticket

**Comment by tcleenewerck** [comment]
@psvensson I was able to compile the ssl libraries on the pi. After adding them to lib folder, everything worked fine.

**Comment by psvensson** [comment]
OK, great!
